version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - airi
  - bumpp
  - changelogithub
  - chromatic
  - culori
  - oklch
  - PREFLIGHTS
  - taze
  - tsdown
  - unocss
  - unplugin
ignoreWords: []
import: []
